[versions]
java = "21"
kotlin = "2.2.21"
junit = "6.0.0"
kover = "0.9.1"
assertj = "3.27.6"
kotlin-logging = "7.0.13"
kotest = "6.0.4"
slf4j = "2.0.17"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[libraries]
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

[bundles]
implementation = [
  "kotlin-logging-jvm",
  "slf4j",
]

test-implementation = [
  "kotest-assertions-core",
  "kotlin-test",
  "junit-jupiter-params",
  "assertj-core",
]
